# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78e3767176f739a0da714fd67e05f2b051b893317ffbbf726e1268964fef2dbeea4872f80c18763bcba4ab9bff3c0e8dfdd4cf5a45d2d7b0ab272a0eb78d8bbd

test:
  secret_key_base: a62d8f9f33298ab7225a1ece210bba35e56815341d14c7f6f04c8523a9868cd27de5709b823299f0164eb2afdbba8fd2e3746b18a104b9f6e8de290f46471e74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
